require:
  - rubocop-rails

AllCops:
  TargetRubyVersion: 2.7

Metrics/BlockLength:
  Exclude:
    - spec/**/*.rb
    - db/**/*

Metrics/MethodLength:
  Exclude:
    - spec/**/*.rb
    - db/**/*

Metrics/AbcSize:
  Exclude:
    - spec/**/*.rb
    - db/**/*

Style/Documentation:
  Enabled: false